name: bye_bye_cry_new
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.9+9

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  intl: ^0.18.0
  flutter_svg: ^1.1.6
  flutter_riverpod: ^2.1.3
  audioplayers: ^3.0.1
  #firebase_auth: ^4.2.5
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.4.2
  #firebase_core: ^2.4.1
  #firebase_storage: ^11.0.10
  #cloud_firestore: ^4.3.1
  shared_preferences: ^2.0.17
  flutter_screen_wake: ^1.0.2
  carousel_slider: ^4.2.1
  purchases_flutter: ^4.9.1
  perfect_volume_control: ^1.0.5
  fluttertoast: ^8.2.1
  firebase_core: ^2.7.1
  firebase_storage: ^11.0.15
  flutter_launcher_icons: ^0.12.0
  path_provider: ^2.0.13
  dio: ^5.0.2
  hexcolor: ^3.0.1
  flutter_inappwebview: ^5.7.2+3
  screen_brightness: ^0.2.2
  just_audio: ^0.9.32
  audio_service: ^0.18.9
  sqflite: ^2.2.6
  favorite_button: ^0.0.4
  get: ^4.6.5
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  callkeep: ^0.3.3
  flutter_system_ringtones: ^0.0.6
  audio_session: ^0.1.13
  lecle_volume_flutter: ^0.0.1+1
  flutter_carousel_slider: ^1.1.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  hive_generator:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/images/newlogo.png"
  min_sdk_android: 21

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # To add asset to your application, add an asset section, like this:
  assets:
    - asset/images/
    - asset/images/icon_png/
    - asset/images/sounds_image/
    - asset/images/icon_png/now_playing_icon/
    - assets/babyCry/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding asset from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Neue Einstellung
      fonts:
        - asset: asset/fonts/NeueEinstellung-Normal.otf
        - asset: asset/fonts/Neue Einstellung Bold.ttf
        - asset: asset/fonts/f0174917-35f6-45fd-bd28-21254c0a6102.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
